irods_host: data.cyverse.org
irods_port: 1247
irods_user_name: iychoi
irods_zone_name: iplant
irods_user_password: 

foreground: false
allow_other: false

path_mappings:
  - irods_path: /iplant/home/iychoi/datasets/POV
    mapping_path: /pov
    resource_type: dir
  - irods_path: /iplant/home/iychoi/datasets/MSSA_MRSA
    mapping_path: /mssa_mrsa
    resource_type: dir

cache:
  metadata_timeout_settings:
    - path: "/"
      timeout: -1
    - path: "/iplant"
      timeout: -1
    - path: "/iplant/home"
      timeout: -1
    - path: "/iplant/home/shared"
      timeout: -1
    - path: "/iplant/home/shared/*"
      timeout: 3600
