name: Release iRODS FUSE Lite
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm, arm64]
    env:
      PKG: "github.com/cyverse/irodsfs"
    steps:
    - name: "set build date"
      run: echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.31
      with:
        github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        goversion: 1.18
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/"
        binary_name: "irodsfs"
        extra_files: LICENSE README.md
        ldflags: "-X '${PKG}/commons.clientVersion=${GITHUB_REF}' -X '${PKG}/commons.gitCommit=${GITHUB_SHA}' -X '${PKG}/commons.buildDate=${BUILD_DATE}'"
